---
# Icinga2 currently supports only two endpoints.
# https://github.com/Icinga/icinga2/issues/3533
- name: Fail when more than 2 icinga2 endpoints are defined
  ansible.builtin.fail:
    msg: No more than 2 endpoints allowed
  when: icinga2_client_monitoring_parents | length > 2

- name: Install icinga2 configuration
  ansible.builtin.template:
    src: templates/etc/icinga2/icinga2.conf.j2
    dest: /etc/icinga2/icinga2.conf
    owner: "{{ icinga2_client_file_owner }}"
    group: "{{ icinga2_client_file_group }}"
    mode: "0644"
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  notify: Icinga2_client reload icinga2

- name: Install icinga2 constants configuration
  ansible.builtin.template:
    src: templates/etc/icinga2/constants.conf.j2
    dest: /etc/icinga2/constants.conf
    owner: "{{ icinga2_client_file_owner }}"
    group: "{{ icinga2_client_file_group }}"
    mode: "0644"
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  notify: Icinga2_client reload icinga2

- name: Install icinga2 zones configuration
  ansible.builtin.template:
    src: templates/etc/icinga2/zones.conf.j2
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_client_file_owner }}"
    group: "{{ icinga2_client_file_group }}"
    mode: "0644"
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  notify: Icinga2_client reload icinga2

- name: Configure icinga2 api feature
  ansible.builtin.template:
    src: templates/etc/icinga2/features-available/api.conf.j2
    dest: /etc/icinga2/features-available/api.conf
    owner: "{{ icinga2_client_file_owner }}"
    group: "{{ icinga2_client_file_group }}"
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0

- name: Enable icinga2 api feature
  ansible.builtin.file:
    src: /etc/icinga2/features-available/api.conf
    dest: /etc/icinga2/features-enabled/api.conf
    mode: "0640"
    state: link

- name: Disable the notification feature
  ansible.builtin.file:
    name: /etc/icinga2/features-enabled/notification.conf
    state: absent
  notify: Icinga2_client reload icinga2
